//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoCGB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class alquiler
    {
        public int id_alquiler { get; set; }

        [Required]
        [Range(1, 365, ErrorMessage = "La duración debe estar entre 1 y 365 días")]
        [Display(Name = "Duración en días")]
        public int duracion_dias { get; set; }

        [Required]
        [Display(Name = "Tipo seguro")]
        [MaxLength(50, ErrorMessage = "No puede superar los 50 caracteres")]      
        public string tipo_seguro { get; set; }

        [Required]
        [Display(Name = "Precio")]
        public decimal precio { get; set; }

        [Required]
        [Display(Name = "DNI condcutor")]
        public int id_conductor { get; set; }

        [Required]
        [Display(Name = "Patente")]
        public int id_coche { get; set; }

    
        public virtual coche coche { get; set; }
        public virtual conductor conductor { get; set; }
    }
}
