//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoCGB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class conductor
    {
        public conductor()
        {
            this.alquiler = new HashSet<alquiler>();
        }
    
        public int id_conductor { get; set; }

        [Required]
        [Display]
        [Range(1, int.MaxValue, ErrorMessage = "El valor debe ser númerico")]
        public int DNI { get; set; }

        [Required]
        [RegularExpression("^[A-Z0-9 a-z]*$", ErrorMessage = "Use solamente letras")]
        [Display(Name = "Nombre y apellido del conductor")]
        [MaxLength(50, ErrorMessage = "No puede superar los 50 caracteres")]       
        public string nombre_conductor { get; set; }

        [Required]
        [Display(Name = "Dirección")]
        [MaxLength(50, ErrorMessage = "No puede superar los 50 caracteres")] //error: error en la base de datos en la cual puse char(20)
        public string direccion { get; set; }

        [Required]
        [Display(Name = "Teléfono contacto")]
        [MaxLength(50, ErrorMessage = "No puede superar los 50 caracteres")]       
        public string telefono_contacto { get; set; }

        [Required]
        [Display(Name = "Tarjeta de crédito")]
        [Range(1, long.MaxValue, ErrorMessage = "El valor debe ser númerico")] //para asegurarme que sea número
        public Nullable<long> nro_tarjeta_credito { get; set; }
    
        public virtual ICollection<alquiler> alquiler { get; set; }
    }
}
